extends GridContainer

#ANALISAR SE OS HORÁRIOS BATEM, PARA NAO PREFERIR UM HORARIO E TMB NAO PREFERIR ESSE MSM HORARIO

#ANALISAR SE OS ITENS FORAM PREENCHIDOS CORRETAMENTE

onready var QUER = {
	'segunda': [$"DIAS/Segunda/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/1",$"DIAS/Segunda/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/2",$"DIAS/Segunda/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/3",$"DIAS/Segunda/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/4",$"DIAS/Segunda/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/5",$"DIAS/Segunda/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/6",$"DIAS/Segunda/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/7"],
	'terca': [$"DIAS/Terça/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/1",$"DIAS/Terça/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/2",$"DIAS/Terça/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/3",$"DIAS/Terça/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/4",$"DIAS/Terça/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/5",$"DIAS/Terça/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/6",$"DIAS/Terça/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/7"],
	'quarta': [$"DIAS/Quarta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/1",$"DIAS/Quarta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/2",$"DIAS/Quarta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/3",$"DIAS/Quarta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/4",$"DIAS/Quarta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/5",$"DIAS/Quarta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/6",$"DIAS/Quarta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/7"],
	'quinta': [$"DIAS/Quinta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/1",$"DIAS/Quinta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/2",$"DIAS/Quinta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/3",$"DIAS/Quinta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/4",$"DIAS/Quinta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/5",$"DIAS/Quinta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/6",$"DIAS/Quinta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/7"],
	'sexta': [$"DIAS/Sexta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/1",$"DIAS/Sexta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/2",$"DIAS/Sexta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/3",$"DIAS/Sexta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/4",$"DIAS/Sexta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/5",$"DIAS/Sexta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/6",$"DIAS/Sexta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/HORARIOS/7"],
	'segunda-motivo': [$"DIAS/Segunda/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/TextEdit"],
	'terca-motivo': [$"DIAS/Terça/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/TextEdit"],
	'quarta-motivo': [$"DIAS/Quarta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/TextEdit"],
	'quinta-motivo': [$"DIAS/Quinta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/TextEdit"],
	'sexta-motivo': [$"DIAS/Sexta/PREFERENCIAS/QUER/HORARIOS_QUE_PREFERE/TextEdit"],
}

onready var NAO_QUER = {
	'segunda': [$"DIAS/Segunda/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/1",$"DIAS/Segunda/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/2",$"DIAS/Segunda/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/3",$"DIAS/Segunda/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/4",$"DIAS/Segunda/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/5",$"DIAS/Segunda/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/6",$"DIAS/Segunda/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/7"],
	'terca': [$"DIAS/Terça/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/1",$"DIAS/Terça/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/2",$"DIAS/Terça/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/3",$"DIAS/Terça/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/4",$"DIAS/Terça/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/5",$"DIAS/Terça/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/6",$"DIAS/Terça/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/7"],
	'quarta': [$"DIAS/Quarta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/1",$"DIAS/Quarta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/2",$"DIAS/Quarta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/3",$"DIAS/Quarta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/4",$"DIAS/Quarta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/5",$"DIAS/Quarta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/6",$"DIAS/Quarta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/7"],
	'quinta': [$"DIAS/Quinta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/1",$"DIAS/Quinta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/2",$"DIAS/Quinta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/3",$"DIAS/Quinta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/4",$"DIAS/Quinta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/5",$"DIAS/Quinta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/6",$"DIAS/Quinta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/7"],
	'sexta': [$"DIAS/Sexta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/1",$"DIAS/Sexta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/2",$"DIAS/Sexta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/3",$"DIAS/Sexta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/4",$"DIAS/Sexta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/5",$"DIAS/Sexta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/6",$"DIAS/Sexta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_NAO_PREFERE/HORARIOS/7"],
	'segunda-motivo': [$"DIAS/Segunda/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_PREFERE/TextEdit"],
	'terca-motivo': [$"DIAS/Terça/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_PREFERE/TextEdit"],
	'quarta-motivo': [$"DIAS/Quarta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_PREFERE/TextEdit"],
	'quinta-motivo': [$"DIAS/Quinta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_PREFERE/TextEdit"],
	'sexta-motivo': [$"DIAS/Sexta/PREFERENCIAS/NAO_QUER/HORARIOS_QUE_PREFERE/TextEdit"],
}

func _ready():
	for z in range(0, 10):#FOR Z IN PROFESSORES NO BANCO DE DADOS add item
		$ESCOLHER_PROFESSOR/Professores.add_item(str(z))
	
	self.add_user_signal("NAO_QUER_SIGNAL_EMMITED", ['dia', 'true_false'])
# warning-ignore:return_value_discarded
	self.connect("NAO_QUER_SIGNAL_EMMITED", self, "_on_NAO_QUER_SIGNAL_EMMITED")
	
	self.add_user_signal("QUER_SIGNAL_EMMITED", ['dia', 'true_false'])
# warning-ignore:return_value_discarded
	self.connect("QUER_SIGNAL_EMMITED", self, "_on_QUER_SIGNAL_EMMITED")
	
	self.add_user_signal("MOTIVO_QUER_SIGNAL_EMMITED", ['dia', 'true_false'])
# warning-ignore:return_value_discarded
	self.connect("MOTIVO_QUER_SIGNAL_EMMITED", self, "_on_MOTIVO_QUER_SIGNAL_EMMITED")
	
	self.add_user_signal("MOTIVO_NAO_QUER_SIGNAL_EMMITED", ['dia', 'true_false'])
# warning-ignore:return_value_discarded
	self.connect("MOTIVO_NAO_QUER_SIGNAL_EMMITED", self, "_on_MOTIVO_NAO_QUER_SIGNAL_EMMITED")

func _on_NAO_QUER_SIGNAL_EMMITED(dia, true_false):
	if true_false == true:
		for z in NAO_QUER[dia]:
			z.pressed = false
			z.disabled = true
	else:
		for z in NAO_QUER[dia]:
			z.disabled = false

func _on_QUER_SIGNAL_EMMITED(dia, true_false):
	if true_false == true:
		for z in QUER[dia]:
			z.pressed = false
			z.disabled = true
	else:
		for z in QUER[dia]:
			z.disabled = false

func _on_MOTIVO_QUER_SIGNAL_EMMITED(dia, true_false):
	if true_false == true:
		for z in QUER[dia+'-motivo']:
			z.visible = true
	else:
		for z in QUER[dia+'-motivo']:
			z.visible = false

func _on_MOTIVO_NAO_QUER_SIGNAL_EMMITED(dia, true_false):
	if true_false == true:
		for z in NAO_QUER[dia+'-motivo']:
			z.visible = true
	else:
		for z in NAO_QUER[dia+'-motivo']:
			z.visible = false

